title: Jean-Yves Bourdoncle blog
#excerpt: "Why I decided to blog in Jekyll on GitHub instead of WordPress."
url: "https://jeanyvesbourdoncle.github.io/"
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
