title: Jean-Yves Bourdoncle blog
#excerpt: "Why I decided to blog in Jekyll on GitHub instead of WordPress."
url: "https://Jeanyvesbourdoncle.github.io/"
#url: "Jean-Yves Bourdoncle"
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
